MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "/home/whs/pose_estimation/maskrcnn-benchmark-master/tools/linemod_results/benchvise/8/model_final.pth"
  # WEIGHT: "catalog://Caffe2Detectron/COCO/35861795/e2e_mask_rcnn_R-101-FPN_1x"
  # WEIGHT: "/home/swh/pose_estimation/maskrcnn-benchmark-master/tools/pretrained_resnet101.pkl"
  # WEIGHT: "/home/whs/pose_estimation/maskrcnn-benchmark-master/tools/occluded_linemod/12/model_final.pth"
  WEIGHT: "/home/whs/pose_estimation/maskrcnn-benchmark-master/tools/ycb_video/16/model_final.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 22
  ROI_KEYPOINT_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "KeypointRCNNFeatureExtractor"
    PREDICTOR: "KeypointRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    NUM_CLASSES: 16
    SHARE_BOX_FEATURE_EXTRACTOR: False
  KEYPOINT_ON: True
DATASETS:
  TRAIN: ("coco_linemod_driller_train",)
  TEST: ("coco_linemod_driller_val",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: './linemod_results/driller/8'
